---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: false # Too many permanent TODOs included in the templates
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- script/
- spec/
