---
StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  # EnforcedStyle: trailing
  Enabled: true

LineLength:
  Description: 'Limit lines to 137 characters.'
  Max: 137
  Enabled: true

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Max: 13

ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  CountComments: false  # count full line comments?
  Max: 290

Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: false
