---
# These are OK:

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  Enabled: true

ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  EnforcedStyle: compact
  Enabled: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: false

ExtraSpacing:
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

Eval:
  Enabled: false

# Work on these:

LineLength:
  Description: 'Limit lines to 137 characters.'
  Max: 120
  Enabled: true

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Max: 18 # 27 # 85

AbcSize:
  Max: 23 # 62
