---
# These are OK:

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  Enabled: true

ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  EnforcedStyle: compact
  Enabled: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: false

ExtraSpacing:
  Enabled: false

# Work on these:

LineLength:
  Description: 'Limit lines to 137 characters.'
  Max: 120
  Enabled: true

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true #- false

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Max: 27 # 85

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Max: 9

PerceivedComplexity:
  Max: 11 # 17

ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  CountComments: false  # count full line comments?

AbcSize:
  Max: 48 # 62
